In [2]:
from pymatgen import MPRester
from pymatgen import Structure
from pymatgen import symmetry
import numpy as np
with MPRester("dnNf3TZDVumSw1eQ") as m:

    # Structure for material id
    structure = m.get_structure_by_material_id("mp-661")

In [3]:
from pymatgen.analysis.diffraction.xrd import XRDCalculator

In [4]:
xrd=XRDCalculator('CuKa1') #longueur d onde arrondie dans l énoncé à priori

In [5]:
pattern=xrd.get_pattern(structure)

In [6]:
pattern.hkls #donne la direction des différents pics ainsi que leur multiplicité

[[{'hkl': (1, 0, -1, 0), 'multiplicity': 6}],
 [{'hkl': (0, 0, 0, 2), 'multiplicity': 2}],
 [{'hkl': (1, 0, -1, 1), 'multiplicity': 12}],
 [{'hkl': (1, 0, -1, 2), 'multiplicity': 12}],
 [{'hkl': (2, -1, -1, 0), 'multiplicity': 6}],
 [{'hkl': (1, 0, -1, 3), 'multiplicity': 12}],
 [{'hkl': (2, 0, -2, 0), 'multiplicity': 6}],
 [{'hkl': (2, -1, -1, 2), 'multiplicity': 12}],
 [{'hkl': (2, 0, -2, 1), 'multiplicity': 12}],
 [{'hkl': (0, 0, 0, 4), 'multiplicity': 2}],
 [{'hkl': (2, 0, -2, 2), 'multiplicity': 12}],
 [{'hkl': (1, 0, -1, 4), 'multiplicity': 12}]]

In [7]:
pat=pattern.x #donne les angles 2*theta liés aux pics de diffraction
print(pat)

[33.03345339 35.76557238 37.7016225  49.47591894 58.99871646 65.54134292
 69.30398983 70.94519402 72.16580521 75.77912133 80.5129395  85.18072548]


In [8]:
#1er pic du diffractogramme
print('Angle 2 theta : ')
print(pat[0])
print('Indices de Bravais-Miller hkil : ') #l'indice i est redondant et permet juste de faire apparaitre plus facilement des symétries de permutation
print(pattern.hkls[0][0]['hkl'][:])
print('Indices de Miller hkl : ')
print(np.delete(pattern.hkls[0][0]['hkl'], 2))

Angle 2 theta : 
33.03345338605786
Indices de Bravais-Miller hkil : 
(1, 0, -1, 0)
Indices de Miller hkl : 
[1 0 0]


In [9]:
#2eme pic du diffractogramme
print('Angle 2 theta : ')
print(pat[1])
print('Indices de Bravais-Miller hkil : ')
print(pattern.hkls[1][0]['hkl'][:])
print('Indices de Miller hkl : ')
print(np.delete(pattern.hkls[1][0]['hkl'], 2))

Angle 2 theta : 
35.765572375753536
Indices de Bravais-Miller hkil : 
(0, 0, 0, 2)
Indices de Miller hkl : 
[0 0 2]


In [10]:
#3eme pic du diffractogramme
print('Angle 2 theta : ')
print(pat[2])
print('Indices de Bravais-Miller hkil : ')
print(pattern.hkls[2][0]['hkl'][:])
print('Indices de Miller hkl : ')
print(np.delete(pattern.hkls[2][0]['hkl'], 2))

Angle 2 theta : 
37.70162249707943
Indices de Bravais-Miller hkil : 
(1, 0, -1, 1)
Indices de Miller hkl : 
[1 0 1]


In [11]:
xrd.show_plot(structure)

<Figure size 1600x1000 with 1 Axes>